# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datum_all.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datum_all.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x64\x61tum_all.proto\"_\n\tDatum_all\x12\x10\n\x08wav_file\x18\x01 \x02(\x0c\x12\x18\n\x10\x63\x61ption_original\x18\x02 \x02(\t\x12\x19\n\x11\x63\x61ption_generated\x18\x03 \x03(\t\x12\x0b\n\x03mos\x18\x04 \x02(\x02')
)




_DATUM_ALL = _descriptor.Descriptor(
  name='Datum_all',
  full_name='Datum_all',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wav_file', full_name='Datum_all.wav_file', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caption_original', full_name='Datum_all.caption_original', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caption_generated', full_name='Datum_all.caption_generated', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mos', full_name='Datum_all.mos', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['Datum_all'] = _DATUM_ALL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Datum_all = _reflection.GeneratedProtocolMessageType('Datum_all', (_message.Message,), dict(
  DESCRIPTOR = _DATUM_ALL,
  __module__ = 'datum_all_pb2'
  # @@protoc_insertion_point(class_scope:Datum_all)
  ))
_sym_db.RegisterMessage(Datum_all)


# @@protoc_insertion_point(module_scope)
