# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datum_wav.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datum_wav.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x64\x61tum_wav.proto\"\xcc\x01\n\tDatum_wav\x12\x10\n\x08wav_file\x18\x01 \x02(\x0c\x12\x0c\n\x04tags\x18\x02 \x01(\x0c\x12\x17\n\x0f\x63\x61ption_writing\x18\x03 \x01(\x0c\x12\x17\n\x0f\x63\x61ption_summary\x18\x04 \x01(\x0c\x12\x1a\n\x12\x63\x61ption_paraphrase\x18\x05 \x01(\x0c\x12$\n\x1c\x63\x61ption_attribute_prediction\x18\x06 \x01(\x0c\x12\r\n\x05title\x18\x07 \x01(\x0c\x12\x0e\n\x06\x61uthor\x18\x08 \x01(\x0c\x12\x0c\n\x04year\x18\t \x01(\x05')
)




_DATUM_WAV = _descriptor.Descriptor(
  name='Datum_wav',
  full_name='Datum_wav',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wav_file', full_name='Datum_wav.wav_file', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='Datum_wav.tags', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caption_writing', full_name='Datum_wav.caption_writing', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caption_summary', full_name='Datum_wav.caption_summary', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caption_paraphrase', full_name='Datum_wav.caption_paraphrase', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caption_attribute_prediction', full_name='Datum_wav.caption_attribute_prediction', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='Datum_wav.title', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author', full_name='Datum_wav.author', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='year', full_name='Datum_wav.year', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=224,
)

DESCRIPTOR.message_types_by_name['Datum_wav'] = _DATUM_WAV
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Datum_wav = _reflection.GeneratedProtocolMessageType('Datum_wav', (_message.Message,), dict(
  DESCRIPTOR = _DATUM_WAV,
  __module__ = 'datum_wav_pb2'
  # @@protoc_insertion_point(class_scope:Datum_wav)
  ))
_sym_db.RegisterMessage(Datum_wav)


# @@protoc_insertion_point(module_scope)
