# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datum_mos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datum_mos.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x64\x61tum_mos.proto\"\x18\n\tDatum_mos\x12\x0b\n\x03mos\x18\x04 \x02(\x02')
)




_DATUM_MOS = _descriptor.Descriptor(
  name='Datum_mos',
  full_name='Datum_mos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mos', full_name='Datum_mos.mos', index=0,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=43,
)

DESCRIPTOR.message_types_by_name['Datum_mos'] = _DATUM_MOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Datum_mos = _reflection.GeneratedProtocolMessageType('Datum_mos', (_message.Message,), dict(
  DESCRIPTOR = _DATUM_MOS,
  __module__ = 'datum_mos_pb2'
  # @@protoc_insertion_point(class_scope:Datum_mos)
  ))
_sym_db.RegisterMessage(Datum_mos)


# @@protoc_insertion_point(module_scope)
